// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcbkipknjautiegooqjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjYmtpcGtuamF1dGllZ29vcWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3NTI1MzIsImV4cCI6MjA5MjMyODUzMn0.hrJC28wI5_etuexc_jeq5GvD35aTWTouoLmOkMd52yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});